apiVersion: v1
kind: Pod
metadata:
  name: dbmovie
  labels:
    app.kubernetes.io/name: dbmovie
spec:
  containers:
  - name: dbmovie
    image: postgres:18
    resources:
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: DBNAME
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: PASSWORD


