apiVersion: v1
kind: Pod
metadata:
  name: dbmovie
  labels:
    app: dbmovie
spec:
  containers:
  - name: dbmovie
    image: postgres:18
    resources:
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: DBNAME
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: PASSWORD
    volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: sql-init
      - mountPath: /var/lib/postgresql/18/docker
        name: db-data
  volumes:
    - name: sql-init
      configMap:
        name: sql-init
    - name: db-data
      persistentVolumeClaim:
        claimName: db-pvc


